# ===============================
# Application
# ===============================
spring.application.name=order-service
server.port=8081

# ===============================
# Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/order
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Axon – sans DCB (mode simple pour tests)
# ===============================
axon.axonserver.servers=localhost:8124
axon.axonserver.enabled=true
axon.distributed-command-bus.enabled=false
axon.eventhandling.processors.user.mode=tracking
axon.eventhandling.tokenstore.jpa.enabled=true

# ===============================
# Logging
# ===============================
logging.level.com.orderservice=INFO
logging.level.org.axonframework=INFO
