spring.application.name=Product-Service

spring.datasource.url=jdbc:mysql://localhost:3308/product
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
axon.axonserver.servers=localhost:8124
axon.axonserver.context=default

# Event Store (JPA)
axon.eventstore.jpa.schema-generation.enabled=true

axon.eventhandling.processors.user.mode=tracking

axon.axonserver.token-store-enabled=true


# Event Handling (Tracking Processor)
#axon.eventhandling.processors.user.source=eventStore
#axon.eventhandling.processors.user.initial-segment-count=1
#axon.eventhandling.processors.user.mode=subscribing


# ===============================
# Eureka Client
# ===============================
eureka.client.enabled=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG