# ===============================
# Application
# ===============================
spring.application.name=Product Service
server.port=8080

# ===============================
# Datasource (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/product
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# AXON CONFIGURATION
# ===============================

# Axon Server
axon.axonserver.servers=localhost:8124
axon.axonserver.context=default

# Event Store (JPA)
axon.eventstore.jpa.schema-generation.enabled=true

# Event Handling (Tracking Processor)
axon.eventhandling.processors.user.source=eventStore
axon.eventhandling.processors.user.initial-segment-count=1
axon.eventhandling.processors.user.mode=subscribing